# Generated by Django 4.1.4 on 2022-12-12 12:08

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='عنوان')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 15, 38, 26, 465437), verbose_name='تاریخ و زمان')),
                ('status', models.BooleanField(default=True, verbose_name='انتشار/پیشنویس')),
                ('thumbnail', models.ImageField(default='thumbnail.png', upload_to='thumbnails/', verbose_name='تصویر شاخص')),
                ('remark', ckeditor.fields.RichTextField(null=True, verbose_name='نوشته')),
                ('دسته', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categories')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته ها',
            },
        ),
    ]
